name: Release

on:
  release:
    types:
      - released
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: print Java version
      run: java -version
    - name: Build with Maven
      run: |
        if [[ "$GITHUB_REF" = refs/heads/* ]]; then
            export VERSIONING_GIT_BRANCH=${GITHUB_REF#refs/heads/};
        elif [[ "$GITHUB_REF" = refs/tags/* ]]; then
            export VERSIONING_GIT_TAG=${GITHUB_REF#refs/tags/};
        elif [[ "$GITHUB_REF" = refs/pull/*/merge ]]; then
            export VERSIONING_GIT_BRANCH=${GITHUB_REF#refs/};
            VERSIONING_GIT_BRANCH=${VERSIONING_GIT_BRANCH%/merge};
        fi
        mvn clean deploy -Possrh --settings settings.xml


