name: Release

on:
  release:
    types:
      - released
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.PGP_SECRET }}
        passphrase: ${{ secrets.PGP_PASSPHRASE }}
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8
        server-id: ossrh
        server-username: SONATYPE_USERNAME
        server-password: SONATYPE_PASSWORD
    - name: print Java version
      run: java -version
    - name: Build with Maven
      env:
        PGP_KEYID: ${{ secrets.PGP_KEYID }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      run: |
        if [[ "$GITHUB_REF" = refs/heads/* ]]; then
            export VERSIONING_GIT_BRANCH=${GITHUB_REF#refs/heads/};
        elif [[ "$GITHUB_REF" = refs/tags/* ]]; then
            export VERSIONING_GIT_TAG=${GITHUB_REF#refs/tags/};
        elif [[ "$GITHUB_REF" = refs/pull/*/merge ]]; then
            export VERSIONING_GIT_BRANCH=${GITHUB_REF#refs/};
            VERSIONING_GIT_BRANCH=${VERSIONING_GIT_BRANCH%/merge};
        fi
        mvn -B --no-transfer-progress clean deploy -Possrh
